# Generated by Django 5.2.6 on 2025-09-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_remove_message_chat_chatmessage_delete_chatsession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='user_email',
            field=models.EmailField(default='exit', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='output_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
